name: publish
on: push

jobs:
  codestyle:
    name: codestyle check
    runs-on: ubuntu-latest

    steps:
      - name: run cppcheck
        uses: deep5050/cppcheck-action@master
        with:
          exclude_check: ./build
          enable : warning, style, performance, portability, unusedFunction, missingInclude
          inconclusive : disable

  build:
    name: build project and run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: install gtest
        run: |
          sudo apt-get install libgtest-dev
          cd /usr/src/gtest
          sudo cmake CMakeLists.txt

      - name: build
        working-directory: ${{runner.workspace}}/mail-cpp-hw-2
        shell: bash
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: test
        shell: bash
        run: |
          ctest -V -R

      - name: memcheck
        shell: bash
        run: |
          sudo apt install -y valgrind
          valgrind ctest

      - name: ci coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
