name: publish
on: push

jobs:
  codestyle:
    name: codestyle check
    runs-on: ubuntu-latest

    steps:
      - name: run cppcheck
        uses: deep5050/cppcheck-action@master
        with:
          exclude_check: ./build
          enable : warning, style, performance, portability, unusedFunction, missingInclude
          inconclusive : disable
        env:
          CI: true

  build:
    name: build project and run tests
    runs-on: ubuntu-latest

    steps:
      - name: build
        working-directory: ${{runner.workspace}}
        shell: bash
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: test
        shell: bash
        run: |
          udo apt install -y valgrind
          valgrind ctest -V -R
      
      - env:
          CI: true

  codecov:
    name: ci coverage
    runs-on: ubuntu-latest

    steps:
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
